### ISSUE TITLE
无法在线编辑

### ISSUE THREAD

**Issue by DaiZhaoedu** [hijiangtao/resume#2]
下载下来的压缩包大概有50多GB，文件过大无法上传。之后下载了[texmaker](http://www.xm1math.net/texmaker/download.html),本地编辑只能编辑文件。也不知道如何编辑，请问还有什么编辑的方法吗

**Comment by hijiangtao** [comment]
在线编译可以使用 https://www.sharelatex.com/ 或者 https://www.overleaf.com/ 
项目压缩包不超过40MB，详见 https://github.com/hijiangtao/resume/releases

**Comment by DaiZhaoedu** [comment]
您的那个模板下载下来就有50多g [哭笑]

**Comment by hijiangtao** [comment]
项目压缩包不超过40MB，详见 https://github.com/hijiangtao/resume/releases
