### ISSUE TITLE
Q&A - 不能编译成功

### ISSUE THREAD

**Issue by jeannotes** [hijiangtao/resume#3]
用的最新的release版本,也试过最新提交吃的版本,都不能编译成功,log如下
********************************************
 * XeTeX is required to compile this document.
 * Sorry!
 ********************************************.
\RequireXeTeX ...********************************}
                                                  \endgroup \fi 
l.26 \RequireXeTeX
                  
This error message was generated by an \errmessage
command, so I can't give any explicit help.
Pretend that you're Hercule Poirot: Examine all clues,
and deduce the truth by order and method.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!
! Fatal fontspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX.
! 
! You must change your typesetting engine to, e.g., "xelatex" or
! "lualatex"instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.28 \msg_fatal:nn {fontspec} {cannot-use-pdftex}
                                                 
|'''''''''''''''''''''''''''''''''''''''''''''''
| This is a fatal error: LaTeX will abort.
|...............................................

**Comment by hijiangtao** [comment]
这是因为你使用的编译器不对，将编译器换成 XeLaTeX 再试试。如果你是使用的在线编译，一般点击 Setting - Compiler，可以查到具体选项。

原因详见 <https://tex.stackexchange.com/questions/400825/fontspec-cannot-use-pdftex-on-overleaf>

**Comment by ZJsnowman** [comment]
感谢,原来是编译器的原因.

**Comment by happymondaynkanta** [comment]
I had similar problem while trying to my file on Overleaf. The simple steps are
1. Click on the menu bar to open up more options.
2.  go to Compiler and select "XeLaTex" as your compiler
3.  Then return to your main.tex file and compile your project.

I have attached some pictures below as a guide.

![1](https://user-images.githubusercontent.com/63404097/148756314-0e3ba0c9-4208-4259-8189-02c1ee2d25c7.PNG)
![2](https://user-images.githubusercontent.com/63404097/148756321-6eed1022-256b-4f0e-8ce9-d0f9588a8ea2.PNG)
![3](https://user-images.githubusercontent.com/63404097/148756322-3555c5fb-36fc-4090-8dec-dc7dbfd3d590.PNG)
![4](https://user-images.githubusercontent.com/63404097/148756323-a04ae732-cd29-48e3-b5bc-6928b61adc22.PNG)

**Comment by hijiangtao** [comment]
@happymondaynkanta It seems you are trying to compile a file but not from this repo, since I can't get the context of your template, I suggest you google the keywords that displayed in the logs.

If you meet problems of compiling this repo on overleaf, you can have a look at README https://github.com/hijiangtao/resume/blob/master/README.md , or open a new issue for tracking the problem.

**Comment by sanrignatius-byte** [comment]
<img width="1913" height="931" alt="Image" src="https://github.com/user-attachments/assets/b212f732-6316-4fba-ad25-981853b53798" />您的模板直接导入overleaf后无法编译，请问该如何解决呢？已尝试切换编译器，但是仍然无法生成PDF
